Add tests
Rediska235/music-app pull request #12
Opened 2023-08-21 12:36 UTC by Rediska235

2023-08-29 06:20 UTC, KatsiarynaAnashkevich commented on MusicApp.SongService.Web/Program.cs
> +    private static void Main(string[] args)
why do you decide to wrap code here with main method?

2023-08-29 06:20 UTC, KatsiarynaAnashkevich commented on MusicApp.Tests/SongService/UnitTests/Commands/CreateSongDelayedCommandHandlerTests.cs
> +    public async Task Handle_ShouldReturnSuccessfulTask()
?

2023-08-29 08:59 UTC, Rediska235 commented on MusicApp.SongService.Web/Program.cs
> +    private static void Main(string[] args)
Initially, the program class has an internal modifier and I can’t use it from the tests assembly, so I brought the program class to its normal form and changed the access modifier to public.

2023-08-29 14:22 UTC, Rediska235 commented on MusicApp.Tests/SongService/UnitTests/Commands/CreateSongDelayedCommandHandlerTests.cs
> +    public async Task Handle_ShouldReturnSuccessfulTask()
I forgot about it)

2023-09-06 12:04 UTC, katyalys requested changes

2023-09-06 12:04 UTC, katyalys commented on MusicApp.SongService.Application/CQRS/Commands/CreateSongDelayed/CreateSongDelayedCommandHandler.cs
> +    public CreateSongDelayedCommandHandler(ISongRepository songRepository, IArtistRepository artistRepository, IMapper mapper, IBackgroundJobClient backgroundJobClient)
use formatting

2023-09-06 12:04 UTC, katyalys commented on MusicApp.Tests/SongService/UnitTests/Commands/CreateSongDelayedCommandHandlerTests.cs
> +    public async Task Handle_ShouldReturnSuccessfulTask()
you should use proper test naming

2023-09-08 12:13 UTC, gfady approved these changes

2023-09-11 08:23 UTC, merged